[build]
  publish = "."
  command = "cd \"EXPERIMENT 3/EXPERIMENT 3.1\" && npm install && npm run build && cd \"../EXPERIMENT 3.2\" && npm install && npm run build && cd \"../EXPERIMENT 3.3\" && npm install && npm run build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/experiment-3"
  to = "/EXPERIMENT 3/index.html"
  status = 200


[[redirects]]
  from = "/exp3.1"
  to = "/EXPERIMENT 3/EXPERIMENT 3.1/dist/index.html"
  status = 200

[[redirects]]
  from = "/exp3.2"
  to = "/EXPERIMENT 3/EXPERIMENT 3.2/dist/index.html"
  status = 200

[[redirects]]
  from = "/exp3.3"
  to = "/EXPERIMENT 3/EXPERIMENT 3.3/dist/index.html"
  status = 200
